baseURL = "https://cdkworkshop.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AWS Cloud Development Kit (AWS CDK) Workshop"
theme = "learn"
uglyurls = true
googleAnalytics = "UA-127749520-1"
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Elad Ben-Israel"
description = "AWS Cloud Development Kit (AWS CDK) Workshop"
disableSearch = true
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = true

[[menu.shortcuts]]
name = "<i class='fab fa-twitter fa-lg'></i> @emeshbi"
identifier = "mm"
url = "https://twitter.com/intent/user?screen_name=emeshbi"
weight = 1

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]
