name: Build workshop site

on: [pull_request]

jobs:
  build:
    name: Build using Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hugo dependency
        run: |
          echo "Download hugo-extended"
          wget https://github.com/gohugoio/hugo/releases/download/v0.104.3/hugo_extended_0.104.3_linux-amd64.tar.gz
          echo "Shovel the binary into the PATH"
          sudo tar -C /usr/bin -xf hugo_extended_0.104.3_linux-amd64.tar.gz hugo

      - name: Install NPM dependencies
        working-directory: ./cdkworkshop.com
        run: npm install --frozen-lockfile

      - name: Build site
        working-directory: ./cdkworkshop.com
        run: npm run build
