name: Build workshop site

on: [pull_request]

jobs:
  build:
    name: Build using Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hugo dependency
        run: sudo apt-get install hugo

      - name: Build site
        working-directory: ./workshop
        run: hugo server -D
